language: objective-c
osx_image: xcode7.2
xcode_workspace: Commandant.xcworkspace
xcode_scheme: Commandant
script: script/cibuild
notifications:
  email: false
  slack:
    secure: DBDJCDEfXVb4g1/vziIYpjwCE5dh75SwBGZAcqbk6wOl6KFS9lA+fk/PtAbuXAEkRNr5qv56aQ+NPRnjSdqmhKB9bwywxUI7LA1JlvxAk6HUya0XWLLH0dvkRJG1o6QWiOnZ79gjWvl/VuN/YH9X7SgwdTTA4xush8ogP+ku8YE=
before_deploy:
  - brew update
  - brew install carthage
  - carthage build --no-skip-current --platform mac
  - carthage archive Commandant
deploy:
  provider: releases
  api_key:
    secure: C5x9Hj0fip8nfrke4AhGNDsmpQsjiB/Mbu6yKwW0MFn46cys64uPajKMDmwcK0512h4eW1HxkmKkaiqfv42gN3Qq+iDmmC7+DNSXgZQ/bj2h5O/t85L6Y+JQGhqbZ6XwAoEcyzFvmkbczR+Xtd0RwQR4WUhqIRElmlCfHe20ST8=
  file: Commandant.framework.zip
  skip_cleanup: true
  on:
    repo: Carthage/Commandant
    tags: true
