script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
  include:
    - script: script/cibuild
      os: osx
      osx_image: xcode7.3
      language: objective-c
      env: JOB=Xcode7.3
      xcode_workspace: Commandant.xcworkspace
      xcode_scheme: Commandant
    - script: swift build
      os: osx
      osx_image: xcode7.3
      language: objective-c
      env: JOB=SPM
      before_install:
        - export SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a
        - curl https://swift.org/builds/development/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg -o swift.pkg
        - sudo installer -pkg swift.pkg -target /
        - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
    - script: swift build
      env: JOB=Linux
      sudo: required
      dist: trusty
      language: generic
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
        - export SWIFT_SNAPSHOT=swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a
        - export SWIFT_URL=https://swift.org/builds/development/ubuntu1404/$SWIFT_SNAPSHOT/$SWIFT_SNAPSHOT-ubuntu14.04.tar.gz
        - wget $SWIFT_URL
        - wget $SWIFT_URL.sig
        - gpg --verify $SWIFT_SNAPSHOT-ubuntu14.04.tar.gz.sig
        - tar xzf $SWIFT_SNAPSHOT-ubuntu14.04.tar.gz
        - export PATH="${PWD}/${SWIFT_SNAPSHOT}-ubuntu14.04/usr/bin:${PATH}"
        - cd Commandant

notifications:
  email: false
  slack:
    secure: DBDJCDEfXVb4g1/vziIYpjwCE5dh75SwBGZAcqbk6wOl6KFS9lA+fk/PtAbuXAEkRNr5qv56aQ+NPRnjSdqmhKB9bwywxUI7LA1JlvxAk6HUya0XWLLH0dvkRJG1o6QWiOnZ79gjWvl/VuN/YH9X7SgwdTTA4xush8ogP+ku8YE=
before_deploy:
  - brew update
  - brew install carthage
  - carthage build --no-skip-current --platform mac
  - carthage archive Commandant
deploy:
  provider: releases
  api_key:
    secure: C5x9Hj0fip8nfrke4AhGNDsmpQsjiB/Mbu6yKwW0MFn46cys64uPajKMDmwcK0512h4eW1HxkmKkaiqfv42gN3Qq+iDmmC7+DNSXgZQ/bj2h5O/t85L6Y+JQGhqbZ6XwAoEcyzFvmkbczR+Xtd0RwQR4WUhqIRElmlCfHe20ST8=
  file: Commandant.framework.zip
  skip_cleanup: true
  on:
    repo: Carthage/Commandant
    tags: true
    condition: $JOB = Xcode7.3
